# Generated by Django 3.1.7 on 2021-04-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lore',
            name='group',
            field=models.ManyToManyField(related_name='lore', to='auth.Group'),
        ),
    ]
