# Generated by Django 3.1.7 on 2021-04-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0002_lore_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lore',
            old_name='group',
            new_name='groups',
        ),
    ]
